# Generated by Django 4.1.3 on 2022-11-03 03:21

import api.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, upload_to=api.user.models.upload_avatar_path, verbose_name='Audio file'),
        ),
    ]
